/*
 * Created on 7 oct. 2013 ( Time 10:49:57 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.emn.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "PAYS"
 * 
 * @author Telosys Tools Generator
 * 
 */
@XmlRootElement
// JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY)
// JAXB accessor = getter/setter pair
@Entity
@Table(name = "PAYS", schema = "PASSO")
// Define named queries here
// @NamedQueries ( {
// @NamedQuery ( name="Country.query1", query="SELECT x FROM Country x WHERE  "
// ),
// @NamedQuery ( name="Country.query2", query="SELECT x FROM Country x WHERE  "
// )
// } )
public class Country implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@Column(name = "ID", nullable = false)
	private int id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "NOM", length = 45)
	private String name;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@OneToMany(mappedBy = "country", targetEntity = User.class)
	private List<User> listOfUser;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public Country() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : NOM ( VARCHAR )
	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------
	@XmlTransient
	public void setListOfUser(List<User> listOfUser) {
		this.listOfUser = listOfUser;
	}

	public List<User> getListOfUser() {
		return this.listOfUser;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(id);
		sb.append("|");
		sb.append(name);
		return sb.toString();
	}

}
