/*
 * Created on 7 oct. 2013 ( Time 10:49:51 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a composite Primary Key  

package org.emn.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "COMMANDE"
 * 
 * @author Telosys Tools Generator
 * 
 */
@XmlRootElement
// JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY)
// JAXB accessor = getter/setter pair
@Entity
@Table(name = "COMMANDE", schema = "PASSO")
// Define named queries here
// @NamedQueries ( {
// @NamedQuery ( name="Order.query1", query="SELECT x FROM Order x WHERE  " ),
// @NamedQuery ( name="Order.query2", query="SELECT x FROM Order x WHERE  " )
// } )
public class Order implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
	// ----------------------------------------------------------------------
	@EmbeddedId
	private OrderKey compositePrimaryKey;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public Order() {
		super();
		this.compositePrimaryKey = new OrderKey();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE COMPOSITE KEY
	// ----------------------------------------------------------------------
	public void setUserId(int userId) {
		this.compositePrimaryKey.setUserId(userId);
	}

	public int getUserId() {
		return this.compositePrimaryKey.getUserId();
	}

	public void setArticleId(int articleId) {
		this.compositePrimaryKey.setArticleId(articleId);
	}

	public int getArticleId() {
		return this.compositePrimaryKey.getArticleId();
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		if (compositePrimaryKey != null) {
			sb.append(compositePrimaryKey.toString());
		} else {
			sb.append("(null-key)");
		}
		sb.append("|");
		return sb.toString();
	}

}
