/*
 * Created on 7 oct. 2013 ( Time 10:49:58 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.emn.persistence.services.jpa;

import org.emn.bean.Country ;
import org.emn.persistence.commons.jpa.GenericJpaService;
import org.emn.persistence.services.CountryPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Country" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CountryPersistenceJPA extends GenericJpaService<Country, Integer> implements CountryPersistence {

	/**
	 * Constructor
	 */
	public CountryPersistenceJPA() {
		super(Country.class);
	}

	public Country load( int id ) {
		return super.load( id );
	}

	public boolean delete( int id ) {
		return super.delete( id );
	}

	public boolean delete(Country entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

}
