/*
 * Created on 7 oct. 2013 ( Time 10:49:49 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.emn.persistence.services.jpa;

import org.emn.bean.Item ;
import org.emn.persistence.commons.jpa.GenericJpaService;
import org.emn.persistence.services.ItemPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Item" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ItemPersistenceJPA extends GenericJpaService<Item, Integer> implements ItemPersistence {

	/**
	 * Constructor
	 */
	public ItemPersistenceJPA() {
		super(Item.class);
	}

	public Item load( int id ) {
		return super.load( id );
	}

	public boolean delete( int id ) {
		return super.delete( id );
	}

	public boolean delete(Item entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

}
