/*
 * Created on 7 oct. 2013 ( Time 10:49:54 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.emn.persistence.services.jpa;

import org.emn.bean.Order ;
import org.emn.bean.OrderKey ;
import org.emn.persistence.commons.jpa.GenericJpaService;
import org.emn.persistence.services.OrderPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Order" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrderPersistenceJPA extends GenericJpaService<Order, OrderKey> implements OrderPersistence {

	/**
	 * Constructor
	 */
	public OrderPersistenceJPA() {
		super(Order.class);
	}

	public Order load( int userId, int articleId ) {
		// Build the composite key
		OrderKey key = new OrderKey( userId, articleId );
		return super.load( key );
	}

	public boolean delete( int userId, int articleId ) {
		// Build the composite key
		OrderKey key = new OrderKey( userId, articleId );
		return super.delete( key );
	}

	public boolean delete(Order entity) {
		if ( entity != null ) {
			// Build the composite key
			OrderKey key = new OrderKey( entity.getUserId(), entity.getArticleId() );
			return super.delete( key );
		}
		return false ;
	}

}
