
/*
 * Created on 7 oct. 2013 ( Time 10:49:57 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.mock;

import java.util.LinkedList;
import java.util.List;

import org.emn.bean.Country ;
import org.emn.mock.tool.MockValues;

public class CountryMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Country createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Country createInstance( int id ) {
		Country entity = new Country();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfUser( TODO ) ; // List<User> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Country> createList(int count) {
		List<Country> list = new LinkedList<Country>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
