
/*
 * Created on 7 oct. 2013 ( Time 10:49:52 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.mock;

import java.util.LinkedList;
import java.util.List;

import org.emn.bean.Order ;
import org.emn.mock.tool.MockValues;

public class OrderMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Order createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Order createInstance( int userId, int articleId ) {
		Order entity = new Order();
		// Init Primary Key fields
		entity.setUserId( userId) ;
		entity.setArticleId( articleId) ;
		// Init Data fields
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Order> createList(int count) {
		List<Order> list = new LinkedList<Order>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
