
/*
 * Created on 7 oct. 2013 ( Time 10:50:02 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.mock;

import java.util.LinkedList;
import java.util.List;

import org.emn.bean.User ;
import org.emn.mock.tool.MockValues;

public class UserMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public User createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public User createInstance( int id ) {
		User entity = new User();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setLogin( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setFirstName( mockValues.nextString(30) ) ; // java.lang.String 
		entity.setAddress( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setZipCode( mockValues.nextString(5) ) ; // java.lang.String 
		entity.setCity( mockValues.nextString(30) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setCountry( TODO ) ; // Country 
		// setListOfItem( TODO ) ; // List<Item> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<User> createList(int count) {
		List<User> list = new LinkedList<User>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
