/*
 * Created on 7 oct. 2013 ( Time 10:50:00 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.test.persistence;

import junit.framework.TestCase;

import org.emn.bean.Country;
import org.emn.mock.CountryMock;
import org.emn.persistence.PersistenceServiceProvider;
import org.emn.persistence.services.CountryPersistence;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * JUnit test case for Country persistence service
 * 
 * @author Telosys Tools Generator
 * 
 */
public class CountryPersistenceTest extends TestCase {

	private CountryPersistence service;
	private CountryMock mock;
	private Country countryTest;

	/**
	 * <p>
	 * Code exécuté avant les tests.
	 * </p>
	 * 
	 * @throws Exception
	 *             toute exception.
	 */
	@Before
	public void setUp() throws Exception {
		service = PersistenceServiceProvider
				.getService(CountryPersistence.class);
		mock = new CountryMock();
		countryTest = service.load(0);
		if (countryTest == null) {
			countryTest = mock.createInstance(0);
			service.insert(countryTest);
		}
	}

	/**
	 * <p>
	 * Code exécuté après les tests.
	 * </p>
	 * 
	 * @throws Exception
	 *             toute exception.
	 */
	@After
	public void tearDown() throws Exception {
		if (service.load(0) != null) {
			service.delete(0);
		}
		if (service.load(1) != null) {
			service.delete(1);
		}
	}

	@Test
	public void testInsertCountry() {
		System.out.println(" ----- ");
		System.out.println(" Test insert : ");

		Country country = mock.createInstance(1);
		service.insert(country);
		Country countryLoad = service.load(1);
		Assert.assertEquals(country.toString(), countryLoad.toString());
		service.delete(1);
	}

	@Test
	public void testLoadCountry() {
		System.out.println(" ----- ");
		System.out.println(" Test load : ");

		Country countryLoad = service.load(0);
		Assert.assertEquals(countryTest.toString(), countryLoad.toString());
	}

	@Test
	public void testDeleteCountry() {
		System.out.println(" ----- ");
		System.out.println(" Test delete : ");

		boolean deleted = service.delete(countryTest);
		Assert.assertTrue(deleted);
	}
}
