/*
 * Created on 7 oct. 2013 ( Time 10:49:51 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.test.persistence;


import org.emn.bean.Item ;
import org.emn.mock.ItemMock;
import org.emn.persistence.PersistenceServiceProvider;
import org.emn.persistence.services.ItemPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Item persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ItemPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Item persistence : delete + load ..." );
		
		ItemPersistence service = PersistenceServiceProvider.getService(ItemPersistence.class);
		
		ItemMock mock = new ItemMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(ItemPersistence service, ItemMock mock, int id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Item entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
