/*
 * Created on 7 oct. 2013 ( Time 10:49:51 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.test.persistence;


import junit.framework.TestCase;

import org.emn.bean.Country;
import org.emn.bean.Item ;
import org.emn.mock.ItemMock;
import org.emn.persistence.PersistenceServiceProvider;
import org.emn.persistence.services.ItemPersistence;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * JUnit test case for Item persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ItemPersistenceTest extends TestCase{

	private ItemPersistence service;
	private ItemMock mock;
	private Item itemTest;

	/**
	 * <p>Code exécuté avant les tests.</p>
	 * @throws Exception toute exception.
	 */
	@Before
	public void setUp() throws Exception {
		service = PersistenceServiceProvider.getService(ItemPersistence.class);
		mock = new ItemMock();
	}

	/**
	 * <p>Code exécuté après les tests.</p>
	 * @throws Exception toute exception.
	 */
	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testInsertItem(){
	}		

	@Test
	public void testLoadItem(){
	}

	@Test
	public void testDeleteItem(){
	}

	private void process(ItemPersistence service, ItemMock mock, int id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Item entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );

			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
