/*
 * Created on 7 oct. 2013 ( Time 10:49:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.test.persistence;


import junit.framework.TestCase;

import org.emn.bean.Order ;
import org.emn.mock.ItemMock;
import org.emn.mock.OrderMock;
import org.emn.persistence.PersistenceServiceProvider;
import org.emn.persistence.services.ItemPersistence;
import org.emn.persistence.services.OrderPersistence;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * JUnit test case for Order persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrderPersistenceTest extends TestCase {

	private OrderPersistence service;
	private OrderMock mock;
	private Order orderTest;

	/**
	 * <p>Code exécuté avant les tests.</p>
	 * @throws Exception toute exception.
	 */
	@Before
	public void setUp() throws Exception {
		service = PersistenceServiceProvider.getService(OrderPersistence.class);
		mock = new OrderMock();
	}

	/**
	 * <p>Code exécuté après les tests.</p>
	 * @throws Exception toute exception.
	 */
	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testLoadDeleteOrder() {

		System.out.println("Test Order persistence : delete + load ..." );

		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(OrderPersistence service, OrderMock mock, int userId, int articleId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Order entity = service.load( userId, articleId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );

			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( userId, articleId ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			 */

			System.out.println(" . delete : " );
			boolean deleted = service.delete( userId, articleId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
