/*
 * Created on 7 oct. 2013 ( Time 10:49:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.emn.test.persistence;


import org.emn.bean.Order ;
import org.emn.mock.OrderMock;
import org.emn.persistence.PersistenceServiceProvider;
import org.emn.persistence.services.OrderPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Order persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrderPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Order persistence : delete + load ..." );
		
		OrderPersistence service = PersistenceServiceProvider.getService(OrderPersistence.class);
		
		OrderMock mock = new OrderMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(OrderPersistence service, OrderMock mock, int userId, int articleId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Order entity = service.load( userId, articleId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( userId, articleId ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( userId, articleId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
