CREATE SCHEMA PASSO;

CREATE TABLE PASSO.UTILISATEUR (
		ID INTEGER NOT NULL,
		LOGIN VARCHAR(30) DEFAULT NULL,
		PASS VARCHAR(20) DEFAULT NULL,
		NOM VARCHAR(40) DEFAULT NULL,
		PRENOM VARCHAR(30) DEFAULT NULL,
		ADRESSE VARCHAR(100) DEFAULT NULL,
		CODE_POSTAL VARCHAR(5) DEFAULT NULL,
		VILLE VARCHAR(30) DEFAULT NULL,
		PAYS_ID INTEGER NOT NULL
	);

CREATE TABLE PASSO.ARTICLE (
		ID INTEGER NOT NULL,
		CODE VARCHAR(5) DEFAULT NULL,
		NOM VARCHAR(50) DEFAULT NULL,
		PRIX DOUBLE DEFAULT NULL,
		STOCK INTEGER DEFAULT NULL
	);

CREATE TABLE PASSO.PAYS (
		ID INTEGER NOT NULL,
		NOM VARCHAR(45)
	);
	
CREATE TABLE PASSO.COMMANDE (
		USER_ID INTEGER NOT NULL,
		ARTICLE_ID INTEGER NOT NULL
		);

CREATE UNIQUE INDEX SQL131007094846730 ON PASSO.ARTICLE (ID ASC);

ALTER TABLE PASSO.UTILISATEUR ADD CONSTRAINT SQL131007101003480 PRIMARY KEY (ID);

ALTER TABLE PASSO.ARTICLE ADD CONSTRAINT SQL131007094846730 PRIMARY KEY (ID);

ALTER TABLE PASSO.COMMANDE ADD CONSTRAINT SQL131007100805140 PRIMARY KEY (USER_ID, ARTICLE_ID);

ALTER TABLE PASSO.PAYS ADD CONSTRAINT SQL131007100824620 PRIMARY KEY (ID);

ALTER TABLE PASSO.COMMANDE ADD CONSTRAINT SQL131007101751500 FOREIGN KEY (USER_ID)
	REFERENCES PASSO.UTILISATEUR (ID);

ALTER TABLE PASSO.COMMANDE ADD CONSTRAINT SQL131007101601560 FOREIGN KEY (ARTICLE_ID)
	REFERENCES PASSO.ARTICLE (ID);

ALTER TABLE PASSO.UTILISATEUR ADD CONSTRAINT SQL131007101930860 FOREIGN KEY (PAYS_ID)
	REFERENCES PASSO.PAYS (ID);

----------------------	
-- Ajout de données --
----------------------
-- ARTICLE
INSERT INTO PASSO.ARTICLE (STOCK, PRIX, NOM, CODE, ID)
VALUES (1, 19.21, 'Article de test', 'ABC01', 43);

INSERT INTO PASSO.ARTICLE (STOCK, PRIX, NOM, CODE, ID)
VALUES (1, 19.21, 'Article de test 2', 'ABC02', 44);

-- PAYS
INSERT INTO PASSO.PAYS (NOM, ID)
VALUES ('FRANCE',45);

INSERT INTO PASSO.PAYS (NOM, ID)
VALUES ('ANGLETERRE',46);

INSERT INTO PASSO.PAYS (NOM, ID)
VALUES ('ALLEMAGNE',47);

-- USER
INSERT INTO PASSO.UTILISATEUR (ID, LOGIN, PASS, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE, PAYS_ID)
VALUES (45,'login','pass','nom','prenom','adresse','44000','NANTES',45);

INSERT INTO PASSO.UTILISATEUR (ID, LOGIN, PASS, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE, PAYS_ID)
VALUES (46,'der','kallen','heinz','frantz','56 Luisenstraße','10115','BERLIN',46);

-- COMMANDE
INSERT INTO PASSO.COMMANDE (ARTICLE_ID, USER_ID)
VALUES (43,45);